name: "Connect to AKS"
description: "Connect runner to a Azure Kubernetes Service cluster on the Azure Cloud Platform"
branding:
  icon: "anchor"
  color: "gray-dark"
inputs:
  CREDENTIALS:
    description: "Credentials for the Azure service principal, preferably a service account specifically for use in Github Actions"
    required: true
  RESOURCE_GROUP:
    description: "The resource group in which the cluster is located"
    required: true
  CLUSTER:
    description: "The name of the cluster to which to connect"
    required: true
  HELM_VERSION:
    description: "The version of helm to install (Example: 'v2' or 'v3')"
    required: false
    default: "v3.12.3"
runs:
  using: "composite"
  steps:
    - name: Check inputs
      id: check-inputs
      shell: bash
      run: |
        ALL_SET=true
        if [ -z "${{ inputs.CREDENTIALS }}" ]; then
          echo "CREDENTIALS input is required"
          ALL_SET=false
        fi
        if [ -z "${{ inputs.RESOURCE_GROUP }}" ]; then
          echo "RESOURCE_GROUP input is required"
          ALL_SET=false
        fi
        if [ -z "${{ inputs.CLUSTER }}" ]; then
          echo "CLUSTER input is required"
          ALL_SET=false
        fi
        if [ "$ALL_SET" = false ]; then
          exit 1
        fi

    - name: Azure login
      id: login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.CREDENTIALS }}
        enable-AzPSSession: true

    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: "${{ inputs.RESOURCE_GROUP }}"
        cluster-name: "${{ inputs.CLUSTER }}"

    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3

    - name: Setup helm
      id: install-helm
      uses: azure/setup-helm@v3
      with: 
        version: ${{ inputs.HELM_VERSION }}
